# USB Gadget Configuration
# This file is read by setup_gadget_composite.sh
# Edit to change which keyboard to emulate

VID=0x046d
PID=0x4049
PI_MANUFACTURER="Logitech"
PI_PRODUCT="Dell WK636 Keyboard"

